// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OwnedTypeTest.Data;

#nullable disable

namespace OwnedTypeTest.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220102161145_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OwnedTypeTest.Data.Models.EntityOwnsOneOfEach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WithBoth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "a@alpha.com",
                            Name = "Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Address = "b@bravo.com",
                            Name = "Bravo"
                        },
                        new
                        {
                            Id = 3,
                            Address = "c@charlie.com",
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Address = "d@delta.com",
                            Name = "Delta"
                        },
                        new
                        {
                            Id = 5,
                            Address = "e@echo.com",
                            Name = "Echo"
                        },
                        new
                        {
                            Id = 6,
                            Address = "f@foxtrot.com",
                            Name = "Foxtrot"
                        },
                        new
                        {
                            Id = 7,
                            Address = "g@golf.com",
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 8,
                            Address = "h@hotel.com",
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 9,
                            Address = "i@india.com",
                            Name = "India"
                        },
                        new
                        {
                            Id = 10,
                            Address = "j@juliet.com",
                            Name = "Juliet"
                        },
                        new
                        {
                            Id = 11,
                            Address = "k@kilo.com",
                            Name = "Kilo"
                        },
                        new
                        {
                            Id = 12,
                            Address = "l@lima.com",
                            Name = "Lima"
                        },
                        new
                        {
                            Id = 13,
                            Address = "m@mike.com",
                            Name = "Mike"
                        },
                        new
                        {
                            Id = 14,
                            Address = "n@november.com",
                            Name = "November"
                        },
                        new
                        {
                            Id = 15,
                            Address = "o@oscar.com",
                            Name = "Oscar"
                        },
                        new
                        {
                            Id = 16,
                            Address = "p@papa.com",
                            Name = "Papa"
                        },
                        new
                        {
                            Id = 17,
                            Address = "q@quebec.com",
                            Name = "Quebec"
                        },
                        new
                        {
                            Id = 18,
                            Address = "r@romeo.com",
                            Name = "Romeo"
                        },
                        new
                        {
                            Id = 19,
                            Address = "s@sierra.com",
                            Name = "Sierra"
                        },
                        new
                        {
                            Id = 20,
                            Address = "t@tango.com",
                            Name = "Tango"
                        },
                        new
                        {
                            Id = 21,
                            Address = "u@uniform.com",
                            Name = "Uniform"
                        },
                        new
                        {
                            Id = 22,
                            Address = "v@victor.com",
                            Name = "Victor"
                        },
                        new
                        {
                            Id = 23,
                            Address = "w@whiskey.com",
                            Name = "Whiskey"
                        },
                        new
                        {
                            Id = 24,
                            Address = "x@x-ray.com",
                            Name = "X-Ray"
                        },
                        new
                        {
                            Id = 25,
                            Address = "y@yankee.com",
                            Name = "Yankee"
                        },
                        new
                        {
                            Id = 26,
                            Address = "z@zulu.com",
                            Name = "Zulu"
                        });
                });

            modelBuilder.Entity("OwnedTypeTest.Data.Models.EntityOwnsOneTableSplitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WithOnes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "a@alpha.com",
                            Name = "Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Address = "b@bravo.com",
                            Name = "Bravo"
                        },
                        new
                        {
                            Id = 3,
                            Address = "c@charlie.com",
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Address = "d@delta.com",
                            Name = "Delta"
                        },
                        new
                        {
                            Id = 5,
                            Address = "e@echo.com",
                            Name = "Echo"
                        },
                        new
                        {
                            Id = 6,
                            Address = "f@foxtrot.com",
                            Name = "Foxtrot"
                        },
                        new
                        {
                            Id = 7,
                            Address = "g@golf.com",
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 8,
                            Address = "h@hotel.com",
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 9,
                            Address = "i@india.com",
                            Name = "India"
                        },
                        new
                        {
                            Id = 10,
                            Address = "j@juliet.com",
                            Name = "Juliet"
                        },
                        new
                        {
                            Id = 11,
                            Address = "k@kilo.com",
                            Name = "Kilo"
                        },
                        new
                        {
                            Id = 12,
                            Address = "l@lima.com",
                            Name = "Lima"
                        },
                        new
                        {
                            Id = 13,
                            Address = "m@mike.com",
                            Name = "Mike"
                        },
                        new
                        {
                            Id = 14,
                            Address = "n@november.com",
                            Name = "November"
                        },
                        new
                        {
                            Id = 15,
                            Address = "o@oscar.com",
                            Name = "Oscar"
                        },
                        new
                        {
                            Id = 16,
                            Address = "p@papa.com",
                            Name = "Papa"
                        },
                        new
                        {
                            Id = 17,
                            Address = "q@quebec.com",
                            Name = "Quebec"
                        },
                        new
                        {
                            Id = 18,
                            Address = "r@romeo.com",
                            Name = "Romeo"
                        },
                        new
                        {
                            Id = 19,
                            Address = "s@sierra.com",
                            Name = "Sierra"
                        },
                        new
                        {
                            Id = 20,
                            Address = "t@tango.com",
                            Name = "Tango"
                        },
                        new
                        {
                            Id = 21,
                            Address = "u@uniform.com",
                            Name = "Uniform"
                        },
                        new
                        {
                            Id = 22,
                            Address = "v@victor.com",
                            Name = "Victor"
                        },
                        new
                        {
                            Id = 23,
                            Address = "w@whiskey.com",
                            Name = "Whiskey"
                        },
                        new
                        {
                            Id = 24,
                            Address = "x@x-ray.com",
                            Name = "X-Ray"
                        },
                        new
                        {
                            Id = 25,
                            Address = "y@yankee.com",
                            Name = "Yankee"
                        },
                        new
                        {
                            Id = 26,
                            Address = "z@zulu.com",
                            Name = "Zulu"
                        });
                });

            modelBuilder.Entity("OwnedTypeTest.Data.Models.EntityOwnsOneToTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WithOnesToTables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "a@alpha.com",
                            Name = "Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Address = "b@bravo.com",
                            Name = "Bravo"
                        },
                        new
                        {
                            Id = 3,
                            Address = "c@charlie.com",
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Address = "d@delta.com",
                            Name = "Delta"
                        },
                        new
                        {
                            Id = 5,
                            Address = "e@echo.com",
                            Name = "Echo"
                        },
                        new
                        {
                            Id = 6,
                            Address = "f@foxtrot.com",
                            Name = "Foxtrot"
                        },
                        new
                        {
                            Id = 7,
                            Address = "g@golf.com",
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 8,
                            Address = "h@hotel.com",
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 9,
                            Address = "i@india.com",
                            Name = "India"
                        },
                        new
                        {
                            Id = 10,
                            Address = "j@juliet.com",
                            Name = "Juliet"
                        },
                        new
                        {
                            Id = 11,
                            Address = "k@kilo.com",
                            Name = "Kilo"
                        },
                        new
                        {
                            Id = 12,
                            Address = "l@lima.com",
                            Name = "Lima"
                        },
                        new
                        {
                            Id = 13,
                            Address = "m@mike.com",
                            Name = "Mike"
                        },
                        new
                        {
                            Id = 14,
                            Address = "n@november.com",
                            Name = "November"
                        },
                        new
                        {
                            Id = 15,
                            Address = "o@oscar.com",
                            Name = "Oscar"
                        },
                        new
                        {
                            Id = 16,
                            Address = "p@papa.com",
                            Name = "Papa"
                        },
                        new
                        {
                            Id = 17,
                            Address = "q@quebec.com",
                            Name = "Quebec"
                        },
                        new
                        {
                            Id = 18,
                            Address = "r@romeo.com",
                            Name = "Romeo"
                        },
                        new
                        {
                            Id = 19,
                            Address = "s@sierra.com",
                            Name = "Sierra"
                        },
                        new
                        {
                            Id = 20,
                            Address = "t@tango.com",
                            Name = "Tango"
                        },
                        new
                        {
                            Id = 21,
                            Address = "u@uniform.com",
                            Name = "Uniform"
                        },
                        new
                        {
                            Id = 22,
                            Address = "v@victor.com",
                            Name = "Victor"
                        },
                        new
                        {
                            Id = 23,
                            Address = "w@whiskey.com",
                            Name = "Whiskey"
                        },
                        new
                        {
                            Id = 24,
                            Address = "x@x-ray.com",
                            Name = "X-Ray"
                        },
                        new
                        {
                            Id = 25,
                            Address = "y@yankee.com",
                            Name = "Yankee"
                        },
                        new
                        {
                            Id = 26,
                            Address = "z@zulu.com",
                            Name = "Zulu"
                        });
                });

            modelBuilder.Entity("OwnedTypeTest.Data.Models.EntityOwnsOneOfEach", b =>
                {
                    b.OwnsOne("OwnedTypeTest.Data.Models.OwnedType", "OwnedType", b1 =>
                        {
                            b1.Property<int>("EntityOwnsOneOfEachId")
                                .HasColumnType("int");

                            b1.Property<string>("MoreCoolData")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("EntityOwnsOneOfEachId");

                            b1.ToTable("WithBoth");

                            b1.WithOwner()
                                .HasForeignKey("EntityOwnsOneOfEachId");
                        });

                    b.OwnsOne("OwnedTypeTest.Data.Models.OwnedTypeTwoWithTable", "OwnedTypeTwoWithTable", b1 =>
                        {
                            b1.Property<int>("EntityOwnsOneOfEachId")
                                .HasColumnType("int");

                            b1.Property<string>("MoreCoolData")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("EntityOwnsOneOfEachId");

                            b1.ToTable("OwnedTypeTwos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EntityOwnsOneOfEachId");
                        });

                    b.Navigation("OwnedType");

                    b.Navigation("OwnedTypeTwoWithTable");
                });

            modelBuilder.Entity("OwnedTypeTest.Data.Models.EntityOwnsOneTableSplitting", b =>
                {
                    b.OwnsOne("OwnedTypeTest.Data.Models.OwnedType", "OwnedType", b1 =>
                        {
                            b1.Property<int>("EntityOwnsOneTableSplittingId")
                                .HasColumnType("int");

                            b1.Property<string>("MoreCoolData")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("EntityOwnsOneTableSplittingId");

                            b1.ToTable("WithOnes");

                            b1.WithOwner()
                                .HasForeignKey("EntityOwnsOneTableSplittingId");
                        });

                    b.Navigation("OwnedType");
                });

            modelBuilder.Entity("OwnedTypeTest.Data.Models.EntityOwnsOneToTable", b =>
                {
                    b.OwnsOne("OwnedTypeTest.Data.Models.OwnedTypeWithTable", "OwnedTypeWithTable", b1 =>
                        {
                            b1.Property<int>("EntityOwnsOneToTableId")
                                .HasColumnType("int");

                            b1.Property<string>("MoreCoolData")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("EntityOwnsOneToTableId");

                            b1.ToTable("OwnedTypes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EntityOwnsOneToTableId");
                        });

                    b.Navigation("OwnedTypeWithTable");
                });
#pragma warning restore 612, 618
        }
    }
}
